version: '3'

networks:
  php80-docker_php:
    external: true

services:
  nginx:
    image: nginxinc/nginx-unprivileged:1.27.5
    restart: always
    user: "${USERID:-1000}:${GID:-0}"
    volumes: 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./http.d:/etc/nginx/http.d
      - ./stream.d:/etc/nginx/stream.d
      - ./certs:/etc/nginx/certs
      - ./htpasswd:/etc/nginx/htpasswd"
      - /opt/www:/opt/www
    working_dir: /etc/nginx
    ports:
      - 80:8080
      - 443:8443
    networks:
      # 为了能使用 php80 访问 php-fpm
      - php80-docker_php
